# Data Exploration Phase of the Project

In [1]:
# Add the Pandas dependency.
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import numpy as np

In [2]:
# Files to load 
ColoradoStateCrime_to_load = "Resources/ColoradoStateCrime_09_19.csv"
DenverCrime_to_load = "Resources/DenverCrime.csv"

In [3]:
# Read the ColoradoStateCrime file and store it in a Pandas DataFrame.
ColoradoStateCrime_df = pd.read_csv(ColoradoStateCrime_to_load)
ColoradoStateCrime_df

,Location Type,Incident Hour of Day,Incident Month,Offense Attempted or Completed,Number of Crimes,Year,Offense Type,Estimated Population,"Crime Rate (per 1,000)","Crime Rate (per 100,000)","Offense Rate (per 1,000)","Offense Rate (per 100,000)","Incident Rate (per 1,000)","Incident Rate (per 100,000)"
0,Residence/Home,Night,January,Attempted,1,2015,Robbery,"5,468,388",0.0,0.02,0.0,0.02,0.0,0.02
1,Residence/Home,Night,January,Completed,15,2015,Robbery,"5,468,388",0.0,0.27,0.0,0.27,0.0,0.27
2,Residence/Home,Night,February,Attempted,5,2015,Robbery,"5,468,388",0.0,0.09,0.0,0.09,0.0,0.09
3,Residence/Home,Night,February,Completed,12,2015,Robbery,"5,468,388",0.0,0.22,0.0,0.22,0.0,0.22
4,Residence/Home,Night,March,Attempted,1,2015,Robbery,"5,468,388",0.0,0.02,0.0,0.02,0.0,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5179,Government/Public Building and other,Day,November,Completed,3,2009,Burglary,5028259,0.0,0.06,0.0,0.06,0.0,0.06
5180,Government/Public Building and other,Day,December,Attempted,0,2009,Burglary,5028259,NaN,NaN,NaN,NaN,NaN,NaN
5181,Government/Public Building and other,Day,December,Completed,6,2009,Burglary,5028259,0.0,0.12,0.0,0.12,0.0,0.12
5182,Government/Public Building and other,Day,December,Attempted,0,2009,Burglary,5028259,NaN,NaN,NaN,NaN,NaN,NaN
5183,Government/Public Building and other,Day,December,Completed,1,2009,Burglary,5028259,0.0,0.02,0.0,0.02,0.0,0.02

In [4]:
# Read the DenverCrime file and store it in a Pandas DataFrame.
DenverCrime_df = pd.read_csv(DenverCrime_to_load)
DenverCrime_df

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,Incident Hour of Day,Incident Month,Number of Crimes,FIRST_OCCURRENCE_DATE,...,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,201985551,2.020000e+14,2203,0,burglary-business-by-force,burglary,Night,February,1,2/6/2019 18:30,...,4655 W KENTUCKY AVE,3127366,1680399,-105.047350,39.700625,4,412,westwood,1,0
1,2017443179,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Day,June,1,6/29/2017 8:00,...,5004 N STUART ST,3128600,1712081,-105.042398,39.787581,1,111,regis,1,0
2,2017248008,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Night,April,1,4/16/2017 21:52,...,4851 N BEACH CT,3135321,1711099,-105.018501,39.784790,1,111,chaffee-park,1,0
3,2017533019,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Day,August,1,8/11/2017 9:15,...,2121 DELGANY ST,3141330,1701365,-104.997312,39.757979,6,612,five-points,1,0
4,2019315865,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Day,May,1,5/20/2019 8:00,...,1415 S VRAIN WAY,3127553,1676889,-105.046748,39.690987,4,421,mar-lee,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21994,2020176458,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Day,August,1,8/1/2019 0:00,...,1374 N OGDEN ST,3147592,1694142,-104.975188,39.738053,6,623,capitol-hill,1,0
21995,2020255311,2.020000e+15,2202,0,burglary-residence-by-force,burglary,Day,September,1,9/29/2019 10:00,...,860 S QUIVAS ST,3138825,1680271,-105.006629,39.700110,4,412,athmar-park,1,0
21996,2020322915,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Night,October,1,10/22/2019 12:00,...,1599 N WILLIAMS ST,3150075,1695369,-104.966334,39.741382,6,622,city-park-west,1,0
21997,2020272897,2.020000e+15,2203,0,burglary-business-by-force,burglary,Night,August,1,8/14/2019 13:00,...,4405 S QUEBEC ST,3167778,1657491,-104.904267,39.637097,3,324,hampden-south,1,0
21998,2020352117,2.020000e+15,2204,0,burglary-residence-no-force,burglary,Day,October,1,10/10/2019 1:00,...,3336 W 46TH AVE,3131862,1709345,-105.030841,39.780024,1,111,berkeley,1,0

### Summary of Descriptive Statistics - Colorado State Crime

In [5]:
#Create a new Series to hold Descriptip Descriptive Statistics - ColoradoStateCrime
ColoradoStateCrime_df.describe()

,Number of Crimes,Year,"Crime Rate (per 1,000)","Crime Rate (per 100,000)","Offense Rate (per 1,000)","Offense Rate (per 100,000)","Incident Rate (per 1,000)","Incident Rate (per 100,000)"
count,5184.000000,5184.000000,4146.000000,4146.000000,4146.000000,4146.000000,4146.000000,4146.000000
mean,43.831404,2014.555556,0.009619,1.024170,0.009619,1.024170,0.009619,1.024170
std,94.282087,3.143000,0.019727,1.934321,0.019727,1.934321,0.019727,1.934321
min,0.000000,2009.000000,0.000000,0.020000,0.000000,0.020000,0.000000,0.020000
25%,1.000000,2012.000000,0.000000,0.060000,0.000000,0.060000,0.000000,0.060000
50%,6.000000,2015.000000,0.000000,0.180000,0.000000,0.180000,0.000000,0.180000
75%,30.000000,2017.000000,0.010000,0.850000,0.010000,0.850000,0.010000,0.850000
max,595.000000,2019.000000,0.110000,11.290000,0.110000,11.290000,0.110000,11.290000

### Summary of Descriptive Statistics - City of Denver Crime

In [6]:
#Create a new Series to hold Descriptip Descriptive Statistics - ColoradoStateCrime
DenverCrime_df.describe()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,Number of Crimes,FIRST_OCCURRENCE_YEAR,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,IS_CRIME,IS_TRAFFIC
count,2.199900e+04,2.199900e+04,21999.000000,21999.000000,21999.0,21999.000000,2.199900e+04,2.199900e+04,21999.000000,21999.000000,21999.000000,21999.000000,21999.0,21999.0
mean,1.976516e+09,1.978512e+15,1987.698986,0.027638,1.0,2017.450930,3.161129e+06,1.693178e+06,-104.934883,39.717613,3.282013,345.332970,1.0,0.0
std,1.833028e+09,1.834779e+15,410.681341,0.163936,0.0,1.118548,6.198970e+05,1.526077e+05,1.734467,0.657240,1.642058,164.575989,0.0,0.0
min,2.017676e+06,2.020000e+12,1202.000000,0.000000,1.0,2016.000000,3.110151e+06,1.649013e+06,-105.108905,0.000001,1.000000,111.000000,1.0,0.0
25%,2.016528e+09,2.020000e+15,2202.000000,0.000000,1.0,2016.000000,3.137858e+06,1.680197e+06,-105.009703,39.699555,2.000000,213.000000,1.0,0.0
50%,2.017654e+09,2.020000e+15,2203.000000,0.000000,1.0,2017.000000,3.146910e+06,1.693599e+06,-104.977667,39.736557,3.000000,321.000000,1.0,0.0
75%,2.018767e+09,2.020000e+15,2204.000000,0.000000,1.0,2018.000000,3.162339e+06,1.701285e+06,-104.922880,39.757618,4.500000,467.000000,1.0,0.0
max,2.020602e+10,2.020000e+16,2206.000000,1.000000,1.0,2019.000000,4.067476e+07,1.089045e+07,-0.000002,39.874789,7.000000,759.000000,1.0,0.0